---
#======================
#==== Kafka Node 3 ====
#======================
version: '2'
services:
  zookeeper-3:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper-3
    container_name: zookeeper-3
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 192.168.120.3:2888:3888;192.168.139.3:2888:3888;0.0.0.0:2888:3888

  kafka-3:
    image: confluentinc/cp-kafka
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 192.168.120.3:2181,192.168.139.3:2181,0.0.0.0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.211.3:9092
