---
#======================
#==== Kafka Node 2 ====
#======================
version: '2'
services:
  zookeeper-2:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper-2
    container_name: zookeeper-2
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 192.168.120.3:2888:3888;0.0.0.0:2888:3888

  kafka-2:
    image: confluentinc/cp-kafka
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 192.168.120.3:2181,0.0.0.0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.139.3:9092
